"""create_initial_schema

Revision ID: aa4573dae325
Revises: 
Create Date: 2026-05-29 11:18:32.381612
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa4573dae325'
down_revision: str | None = None
branch_labels: str | (str, ...) | None = None
depends_on: str | (str, ...) | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_categories',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Machine-readable code matching TariffCategoryCode enum'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable name (e.g., 'LT Domestic')"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    comment='KSEB tariff categories (LT Domestic, LT Commercial, etc.)'
    )
    op.create_index('ix_tariff_categories_code', 'tariff_categories', ['code'], unique=True)
    op.create_index(op.f('ix_tariff_categories_created_at'), 'tariff_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_tariff_categories_id'), 'tariff_categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary login identifier — stored lowercase'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Display name'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='E.164 format phone number for SMS notifications'),
    sa.Column('hashed_password', sa.Text(), nullable=False, comment='bcrypt hash — NEVER store plaintext'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False = account suspended, cannot login'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='True once email is confirmed'),
    sa.Column('role', sa.String(length=50), server_default='CONSUMER', nullable=False, comment='ADMIN | OPERATOR | CONSUMER'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp of last successful login'),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False, comment='Consecutive failed login attempts (reset on success)'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this UTC time after too many failed logins'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp of last password change (for token invalidation)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft-delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of soft deletion (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Platform user accounts with RBAC roles'
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_is_active_deleted', 'users', ['is_active', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False, comment='Name of the affected table'),
    sa.Column('record_id', sa.UUID(), nullable=True, comment='Primary key of the affected row (NULL for bulk operations)'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='INSERT | UPDATE | DELETE | SOFT_DELETE | RESTORE'),
    sa.Column('changed_by_id', sa.UUID(), nullable=True, comment='User who performed the action (NULL for system/automated actions)'),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the change'),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Row state BEFORE the change (NULL for INSERT)'),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Row state AFTER the change (NULL for DELETE)'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='Client IP address (PostgreSQL INET type)'),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='X-Request-ID from the HTTP request (for correlating log lines)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Immutable audit trail for all data mutations'
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_changed_at', 'audit_logs', ['changed_at'], unique=False)
    op.create_index('ix_audit_logs_changed_by', 'audit_logs', ['changed_by_id'], unique=False)
    op.create_index('ix_audit_logs_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_table('devices',
    sa.Column('serial_number', sa.String(length=100), nullable=False, comment='ESP32 factory-assigned unique ID (trust anchor for auth)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable label (e.g., 'Main Panel', 'Kitchen Circuit')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Additional notes about the installation'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='User who owns/manages this device'),
    sa.Column('connection_type', sa.String(length=50), nullable=False, comment='SINGLE_PHASE | THREE_PHASE_BALANCED | THREE_PHASE_UNBALANCED'),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False, comment='Lifecycle state of the device'),
    sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False, comment='Updated by health monitor heartbeat checks'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp of last received telemetry packet'),
    sa.Column('commissioned_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when device moved to ACTIVE status'),
    sa.Column('firmware_version', sa.String(length=50), nullable=True, comment="Semantic version of installed firmware (e.g., '2.1.4')"),
    sa.Column('hardware_version', sa.String(length=50), nullable=True, comment="PCB revision (e.g., 'rev3.0')"),
    sa.Column('timezone', sa.String(length=100), server_default='Asia/Kolkata', nullable=False, comment="IANA timezone (e.g., 'Asia/Kolkata') for TOD classification"),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary key-value tags for grouping/filtering (e.g., building, floor)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft-delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of soft deletion (UTC)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Registered ESP32 smart meter units'
    )
    op.create_index('ix_devices_connection_type', 'devices', ['connection_type'], unique=False)
    op.create_index(op.f('ix_devices_created_at'), 'devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_is_deleted'), 'devices', ['is_deleted'], unique=False)
    op.create_index('ix_devices_last_seen_at', 'devices', ['last_seen_at'], unique=False)
    op.create_index('ix_devices_owner_id', 'devices', ['owner_id'], unique=False)
    op.create_index('ix_devices_owner_status', 'devices', ['owner_id', 'status'], unique=False)
    op.create_index('ix_devices_serial_number', 'devices', ['serial_number'], unique=True)
    op.create_index('ix_devices_status', 'devices', ['status'], unique=False)
    op.create_table('tariff_versions',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Sequential version number within a category (1, 2, 3...)'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='First day this tariff applies (inclusive)'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Last day this tariff applies (inclusive). NULL = currently active'),
    sa.Column('fixed_charge_per_month', sa.Numeric(precision=10, scale=4), nullable=False, comment='Fixed monthly meter rent + service charge in INR'),
    sa.Column('fuel_surcharge_percent', sa.Numeric(precision=7, scale=4), nullable=False, comment='KSEB fuel cost adjustment surcharge (% of energy charges)'),
    sa.Column('electricity_duty_percent', sa.Numeric(precision=7, scale=4), nullable=False, comment='State electricity duty (% of energy charges)'),
    sa.Column('has_tod_pricing', sa.Boolean(), server_default='false', nullable=False, comment='Whether TOD modifiers apply to this tariff version'),
    sa.Column('description', sa.Text(), nullable=True, comment='Reference to gazette notification or official circular'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Admin user who entered this tariff version'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name='ck_tariff_version_date_range'),
    sa.CheckConstraint('electricity_duty_percent >= 0 AND electricity_duty_percent <= 100', name='ck_tariff_version_duty_range'),
    sa.CheckConstraint('fixed_charge_per_month >= 0', name='ck_tariff_version_fixed_charge_nonneg'),
    sa.CheckConstraint('fuel_surcharge_percent >= 0 AND fuel_surcharge_percent <= 100', name='ck_tariff_version_fuel_surcharge_range'),
    sa.ForeignKeyConstraint(['category_id'], ['tariff_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'version_number', name='uq_tariff_versions_cat_version'),
    comment='Versioned tariff rates with gazette effective dates'
    )
    op.create_index('ix_tariff_versions_category_effective', 'tariff_versions', ['category_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_tariff_versions_created_at'), 'tariff_versions', ['created_at'], unique=False)
    op.create_index('ix_tariff_versions_effective_to', 'tariff_versions', ['effective_to'], unique=False)
    op.create_index(op.f('ix_tariff_versions_id'), 'tariff_versions', ['id'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Human-readable label for this key (e.g., 'Grafana Dashboard')"),
    sa.Column('key_hash', sa.String(length=128), nullable=False, comment='SHA-256 hash of the raw key — never store plaintext'),
    sa.Column('key_prefix', sa.String(length=12), nullable=False, comment='First 8 chars of raw key for identification without exposing it'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='NULL = never expires'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Revokable long-lived API keys for service accounts'
    )
    op.create_index('ix_user_api_keys_key_hash', 'user_api_keys', ['key_hash'], unique=True)
    op.create_index('ix_user_api_keys_user_id', 'user_api_keys', ['user_id'], unique=False)
    op.create_table('billing_snapshots',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Denormalized from device for direct consumer queries'),
    sa.Column('tariff_version_id', sa.UUID(), nullable=False, comment='Tariff version used for this specific billing calculation'),
    sa.Column('billing_period_start', sa.Date(), nullable=False, comment='First day of the billing period (inclusive)'),
    sa.Column('billing_period_end', sa.Date(), nullable=False, comment='Last day of the billing period (inclusive)'),
    sa.Column('snapshot_type', sa.String(length=30), nullable=False, comment='PROJECTED_TODAY | PROJECTED_MONTH | FINAL_MONTHLY | CUSTOM'),
    sa.Column('is_projected', sa.Boolean(), server_default='true', nullable=False, comment='True = estimate, False = locked final bill'),
    sa.Column('is_finalized', sa.Boolean(), server_default='false', nullable=False, comment='True = immutable, do not modify'),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_units_kwh', sa.Numeric(precision=14, scale=6), nullable=False, comment='Total kWh consumed in the billing period'),
    sa.Column('day_units_kwh', sa.Numeric(precision=14, scale=6), nullable=False, comment='DAY bucket kWh'),
    sa.Column('peak_units_kwh', sa.Numeric(precision=14, scale=6), nullable=False, comment='PEAK bucket kWh'),
    sa.Column('night_units_kwh', sa.Numeric(precision=14, scale=6), nullable=False, comment='NIGHT bucket kWh'),
    sa.Column('energy_charge_inr', sa.Numeric(precision=12, scale=4), nullable=False, comment='Sum of all slab charges before surcharges'),
    sa.Column('fixed_charge_inr', sa.Numeric(precision=12, scale=4), nullable=False, comment='Monthly fixed charge (pro-rated if period < full month)'),
    sa.Column('fuel_surcharge_inr', sa.Numeric(precision=12, scale=4), nullable=False, comment='Fuel cost adjustment surcharge'),
    sa.Column('electricity_duty_inr', sa.Numeric(precision=12, scale=4), nullable=False, comment='State electricity duty'),
    sa.Column('total_payable_inr', sa.Numeric(precision=12, scale=4), nullable=False, comment='Final payable amount including all charges and taxes'),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full slab-by-slab breakdown for audit. Structure: {slabs: [{order, units_from, units_to, units, rate, charge}], tod_modifiers: {...}, surcharges: {...}}'),
    sa.Column('correction_of_id', sa.UUID(), nullable=True, comment='If this snapshot corrects a previous one, reference the original'),
    sa.Column('correction_reason', sa.Text(), nullable=True, comment="Reason for correction (e.g., 'CT ratio recalibrated')"),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.CheckConstraint('billing_period_end >= billing_period_start', name='ck_billing_period_valid'),
    sa.CheckConstraint('total_payable_inr >= 0', name='ck_billing_payable_nonneg'),
    sa.CheckConstraint('total_units_kwh >= 0', name='ck_billing_units_nonneg'),
    sa.ForeignKeyConstraint(['correction_of_id'], ['billing_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Complete billing calculation snapshots (projected + final)'
    )
    op.create_index('ix_billing_device_period', 'billing_snapshots', ['device_id', 'billing_period_start'], unique=False)
    op.create_index('ix_billing_device_type', 'billing_snapshots', ['device_id', 'snapshot_type'], unique=False)
    op.create_index('ix_billing_is_projected', 'billing_snapshots', ['is_projected'], unique=False)
    op.create_index('ix_billing_owner_period', 'billing_snapshots', ['owner_id', 'billing_period_start'], unique=False)
    op.create_index(op.f('ix_billing_snapshots_created_at'), 'billing_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_snapshots_id'), 'billing_snapshots', ['id'], unique=False)
    op.create_table('device_auth_tokens',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False, comment='SHA-256 of the raw pre-shared key'),
    sa.Column('token_prefix', sa.String(length=12), nullable=False, comment='First 8 chars of the raw key for identification'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this token replaced a previous one'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', name='uq_device_auth_tokens_device_id'),
    comment='Pre-shared HMAC keys for ESP32 device authentication'
    )
    op.create_index(op.f('ix_device_auth_tokens_created_at'), 'device_auth_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_auth_tokens_id'), 'device_auth_tokens', ['id'], unique=False)
    op.create_index('ix_device_auth_tokens_token_hash', 'device_auth_tokens', ['token_hash'], unique=True)
    op.create_table('device_configurations',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('tariff_category_id', sa.UUID(), nullable=True, comment='Which tariff category applies to this installation'),
    sa.Column('voltage_nominal_v', sa.Numeric(precision=8, scale=3), nullable=False, comment='Nominal line voltage in Volts (230 for LT domestic, 415 for 3-phase)'),
    sa.Column('current_rated_a', sa.Numeric(precision=8, scale=3), nullable=False, comment='Rated current capacity of the installation in Amperes'),
    sa.Column('ct_ratio', sa.Numeric(precision=12, scale=6), nullable=False, comment='Current transformer ratio (raw_current × ct_ratio = actual_current)'),
    sa.Column('pt_ratio', sa.Numeric(precision=12, scale=6), nullable=False, comment='Potential transformer ratio (usually 1 for LT)'),
    sa.Column('calibration_factor', sa.Numeric(precision=10, scale=6), nullable=False, comment='Site-specific correction factor (1.0 = no correction)'),
    sa.Column('telemetry_interval_seconds', sa.Integer(), nullable=False, comment='Expected seconds between telemetry packets from this device'),
    sa.Column('max_missing_packets_before_alert', sa.Integer(), nullable=False, comment='How many consecutive missed packets trigger an offline alert'),
    sa.Column('voltage_high_threshold_v', sa.Numeric(precision=8, scale=3), nullable=False, comment='Upper voltage limit in Volts (110% of 230V nominal)'),
    sa.Column('voltage_low_threshold_v', sa.Numeric(precision=8, scale=3), nullable=False, comment='Lower voltage limit in Volts (90% of 230V nominal)'),
    sa.Column('power_factor_low_threshold', sa.Numeric(precision=5, scale=4), nullable=False, comment='Alert when power factor drops below this value'),
    sa.Column('current_high_threshold_a', sa.Numeric(precision=8, scale=3), nullable=True, comment='Overcurrent alert threshold (defaults to current_rated_a × 1.1 if NULL)'),
    sa.Column('phase_imbalance_threshold_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='Alert when any phase differs from average by more than this %'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.CheckConstraint('calibration_factor > 0 AND calibration_factor <= 10', name='ck_device_config_calibration_factor_range'),
    sa.CheckConstraint('ct_ratio > 0', name='ck_device_config_ct_ratio_positive'),
    sa.CheckConstraint('pt_ratio > 0', name='ck_device_config_pt_ratio_positive'),
    sa.CheckConstraint('telemetry_interval_seconds >= 1 AND telemetry_interval_seconds <= 3600', name='ck_device_config_interval_range'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_category_id'], ['tariff_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', name='uq_device_configurations_device_id'),
    comment='Calibration and operational configuration for each device'
    )
    op.create_index(op.f('ix_device_configurations_created_at'), 'device_configurations', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_configurations_id'), 'device_configurations', ['id'], unique=False)
    op.create_table('device_health_records',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this health check was performed'),
    sa.Column('is_online', sa.Boolean(), nullable=False, comment='True if device sent telemetry within the expected interval'),
    sa.Column('last_telemetry_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp of the most recent valid telemetry packet'),
    sa.Column('seconds_since_last_telemetry', sa.Numeric(precision=12, scale=3), nullable=True, comment='Seconds elapsed since last valid packet (used for alert thresholding)'),
    sa.Column('firmware_version', sa.String(length=50), nullable=True, comment='Firmware version reported by device'),
    sa.Column('wifi_rssi_dbm', sa.Integer(), nullable=True, comment='WiFi signal strength in dBm (e.g., -70 = good, -90 = poor)'),
    sa.Column('free_heap_bytes', sa.Integer(), nullable=True, comment='ESP32 free heap memory in bytes'),
    sa.Column('cpu_temperature_c', sa.Numeric(precision=5, scale=2), nullable=True, comment='ESP32 internal temperature sensor in °C'),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True, comment='Device uptime since last reset in seconds'),
    sa.Column('reset_reason', sa.String(length=50), nullable=True, comment='ESP32 reset reason (POWER_ON, WATCHDOG, PANIC, etc.)'),
    sa.Column('packets_last_hour', sa.Integer(), nullable=True, comment='Number of telemetry packets received in the last 60 minutes'),
    sa.Column('expected_packets_last_hour', sa.Integer(), nullable=True, comment='Expected packet count based on configured interval'),
    sa.Column('health_score', sa.Integer(), nullable=True, comment='Composite health score 0–100. 100 = fully healthy, 0 = completely offline/failed. Factors: online status, packet rate, RSSI, heap, anomalies'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Periodic device health snapshots (heartbeat + diagnostics)'
    )
    op.create_index('ix_device_health_device_recorded', 'device_health_records', ['device_id', 'recorded_at'], unique=False)
    op.create_index('ix_device_health_is_online', 'device_health_records', ['is_online'], unique=False)
    op.create_index(op.f('ix_device_health_records_id'), 'device_health_records', ['id'], unique=False)
    op.create_table('device_locations',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='WGS84 latitude'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='WGS84 longitude'),
    sa.Column('installation_notes', sa.Text(), nullable=True),
    sa.Column('installed_by', sa.String(length=255), nullable=True, comment='Name of the installing technician'),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', name='uq_device_locations_device_id'),
    comment='Physical installation location for each device'
    )
    op.create_index(op.f('ix_device_locations_created_at'), 'device_locations', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_locations_id'), 'device_locations', ['id'], unique=False)
    op.create_index('ix_device_locations_pincode', 'device_locations', ['pincode'], unique=False)
    op.create_table('energy_daily_aggregates',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Local date (in device timezone) — NOT UTC date'),
    sa.Column('total_active_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('day_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('peak_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('night_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('avg_voltage_v', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('avg_current_a', sa.Numeric(precision=9, scale=5), nullable=True),
    sa.Column('avg_power_factor', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('min_power_factor', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('reading_count', sa.Integer(), nullable=False),
    sa.Column('missing_intervals_count', sa.Integer(), nullable=False, comment='Number of expected intervals with no data'),
    sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False, comment='True once the day has fully elapsed'),
    sa.Column('gap_filled_wh', sa.Numeric(precision=20, scale=6), nullable=False, comment='Energy from gap-filled intervals (may be less accurate)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'date', name='uq_energy_daily_device_date'),
    comment='Pre-aggregated daily energy in device local timezone'
    )
    op.create_index(op.f('ix_energy_daily_aggregates_created_at'), 'energy_daily_aggregates', ['created_at'], unique=False)
    op.create_index(op.f('ix_energy_daily_aggregates_id'), 'energy_daily_aggregates', ['id'], unique=False)
    op.create_index('ix_energy_daily_device_date', 'energy_daily_aggregates', ['device_id', 'date'], unique=False)
    op.create_table('energy_hourly_aggregates',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('hour_start', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of the start of the hour (truncated to 00:00 of that hour)'),
    sa.Column('total_active_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False, comment='Total Wh this hour'),
    sa.Column('day_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False, comment='DAY bucket Wh'),
    sa.Column('peak_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False, comment='PEAK bucket Wh'),
    sa.Column('night_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False, comment='NIGHT bucket Wh'),
    sa.Column('avg_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True, comment='Average active power this hour (W)'),
    sa.Column('max_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True, comment='Peak active power this hour (W)'),
    sa.Column('min_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True, comment='Minimum active power this hour (W)'),
    sa.Column('avg_voltage_v', sa.Numeric(precision=9, scale=4), nullable=True, comment='Average voltage this hour (V)'),
    sa.Column('avg_power_factor', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('reading_count', sa.Integer(), nullable=False, comment='Number of valid readings this hour'),
    sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False, comment='True once the hour has fully elapsed (locked for modification)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'hour_start', name='uq_energy_hourly_device_hour'),
    comment='Pre-aggregated hourly energy per device'
    )
    op.create_index(op.f('ix_energy_hourly_aggregates_created_at'), 'energy_hourly_aggregates', ['created_at'], unique=False)
    op.create_index(op.f('ix_energy_hourly_aggregates_id'), 'energy_hourly_aggregates', ['id'], unique=False)
    op.create_index('ix_energy_hourly_device_hour', 'energy_hourly_aggregates', ['device_id', 'hour_start'], unique=False)
    op.create_table('energy_monthly_aggregates',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False, comment='1–12'),
    sa.Column('total_active_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False, comment='Total month Wh'),
    sa.Column('day_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('peak_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('night_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('total_active_energy_kwh', sa.Numeric(precision=14, scale=6), nullable=True, comment='total_active_energy_wh / 1000 — stored for convenience'),
    sa.Column('avg_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True, comment='Peak demand this month'),
    sa.Column('avg_power_factor', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('reading_count', sa.Integer(), nullable=False),
    sa.Column('missing_days', sa.Integer(), nullable=False, comment='Days with no data'),
    sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False, comment='True once the calendar month has elapsed'),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True, comment='When the monthly aggregate was locked for billing'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_energy_monthly_month_range'),
    sa.CheckConstraint('year >= 2020 AND year <= 2100', name='ck_energy_monthly_year_range'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'year', 'month', name='uq_energy_monthly_device_year_month'),
    comment='Monthly energy totals per device — primary billing basis'
    )
    op.create_index(op.f('ix_energy_monthly_aggregates_created_at'), 'energy_monthly_aggregates', ['created_at'], unique=False)
    op.create_index(op.f('ix_energy_monthly_aggregates_id'), 'energy_monthly_aggregates', ['id'], unique=False)
    op.create_index('ix_energy_monthly_device_ym', 'energy_monthly_aggregates', ['device_id', 'year', 'month'], unique=False)
    op.create_table('tariff_slabs',
    sa.Column('tariff_version_id', sa.UUID(), nullable=False),
    sa.Column('slab_order', sa.Integer(), nullable=False, comment='1-based ordering of slabs'),
    sa.Column('units_from', sa.Numeric(precision=10, scale=3), nullable=False, comment='Start of slab in kWh (inclusive)'),
    sa.Column('units_to', sa.Numeric(precision=10, scale=3), nullable=True, comment='End of slab in kWh (exclusive). NULL = unbounded (last slab)'),
    sa.Column('rate_per_unit', sa.Numeric(precision=10, scale=4), nullable=False, comment='INR per kWh for consumption within this slab'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.CheckConstraint('rate_per_unit >= 0', name='ck_tariff_slab_rate_nonneg'),
    sa.CheckConstraint('slab_order >= 1', name='ck_tariff_slab_order_positive'),
    sa.CheckConstraint('units_from >= 0', name='ck_tariff_slab_units_from_nonneg'),
    sa.CheckConstraint('units_to IS NULL OR units_to > units_from', name='ck_tariff_slab_units_range'),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'slab_order', name='uq_tariff_slabs_version_order'),
    comment='Rate slabs within a tariff version (kWh tiers)'
    )
    op.create_index(op.f('ix_tariff_slabs_id'), 'tariff_slabs', ['id'], unique=False)
    op.create_index('ix_tariff_slabs_version', 'tariff_slabs', ['tariff_version_id'], unique=False)
    op.create_table('tariff_tod_modifiers',
    sa.Column('tariff_version_id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.String(length=10), nullable=False, comment='DAY | PEAK | NIGHT'),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=4), nullable=False, comment='Rate multiplier (1.0 = no change, 1.2 = 20% surcharge)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.CheckConstraint('multiplier > 0 AND multiplier <= 5.0', name='ck_tariff_tod_modifier_multiplier_range'),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'bucket', name='uq_tariff_tod_modifiers_version_bucket'),
    comment='TOD pricing multipliers per tariff version'
    )
    op.create_index(op.f('ix_tariff_tod_modifiers_id'), 'tariff_tod_modifiers', ['id'], unique=False)
    op.create_table('tariff_tod_windows',
    sa.Column('tariff_version_id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.String(length=10), nullable=False, comment='DAY | PEAK | NIGHT'),
    sa.Column('window_start', sa.Time(), nullable=False, comment='Local time when this bucket starts (e.g., 18:00 for PEAK)'),
    sa.Column('window_end', sa.Time(), nullable=False, comment='Local time when this bucket ends (e.g., 22:00 for PEAK)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'bucket', name='uq_tariff_tod_windows_version_bucket'),
    comment='Time-of-day window boundaries per tariff version (local time)'
    )
    op.create_index(op.f('ix_tariff_tod_windows_id'), 'tariff_tod_windows', ['id'], unique=False)
    op.create_index('ix_tariff_tod_windows_version', 'tariff_tod_windows', ['tariff_version_id'], unique=False)
    op.create_table('telemetry_readings',
    sa.Column('id', sa.UUID(), nullable=False, comment='Immutable row identifier'),
    sa.Column('device_id', sa.UUID(), nullable=False, comment='Source device — RESTRICT prevents orphan deletion'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='Device-local timestamp (from ESP32 RTC) — partition key'),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Server receipt timestamp — delta vs recorded_at reveals clock drift'),
    sa.Column('sequence_number', sa.BigInteger(), nullable=True, comment='Monotonic counter from device firmware for gap detection'),
    sa.Column('connection_type', sa.String(length=50), nullable=False, comment='Copied from device at ingestion time (avoids join on hot path)'),
    sa.Column('phase_a_voltage', sa.Numeric(precision=9, scale=4), nullable=True, comment='Phase A (or single phase) RMS voltage in Volts'),
    sa.Column('phase_a_current', sa.Numeric(precision=9, scale=5), nullable=True, comment='Phase A RMS current in Amperes'),
    sa.Column('phase_a_power_factor', sa.Numeric(precision=6, scale=5), nullable=True, comment='Phase A power factor [-1.0, +1.0]. Negative = leading (capacitive)'),
    sa.Column('phase_b_voltage', sa.Numeric(precision=9, scale=4), nullable=True, comment='Phase B RMS voltage in Volts'),
    sa.Column('phase_b_current', sa.Numeric(precision=9, scale=5), nullable=True, comment='Phase B RMS current in Amperes'),
    sa.Column('phase_b_power_factor', sa.Numeric(precision=6, scale=5), nullable=True, comment='Phase B power factor [-1.0, +1.0]'),
    sa.Column('phase_c_voltage', sa.Numeric(precision=9, scale=4), nullable=True, comment='Phase C RMS voltage in Volts'),
    sa.Column('phase_c_current', sa.Numeric(precision=9, scale=5), nullable=True, comment='Phase C RMS current in Amperes'),
    sa.Column('phase_c_power_factor', sa.Numeric(precision=6, scale=5), nullable=True, comment='Phase C power factor [-1.0, +1.0]'),
    sa.Column('phase_a_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True, comment='P_A = V_A × I_A × PF_A (Watts)'),
    sa.Column('phase_a_apparent_power_va', sa.Numeric(precision=14, scale=4), nullable=True, comment='S_A = V_A × I_A (VA)'),
    sa.Column('phase_a_reactive_power_var', sa.Numeric(precision=14, scale=4), nullable=True, comment='Q_A = √(S_A² - P_A²) (VAR)'),
    sa.Column('phase_b_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True, comment='P_B (Watts)'),
    sa.Column('phase_b_apparent_power_va', sa.Numeric(precision=14, scale=4), nullable=True, comment='S_B (VA)'),
    sa.Column('phase_b_reactive_power_var', sa.Numeric(precision=14, scale=4), nullable=True, comment='Q_B (VAR)'),
    sa.Column('phase_c_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True, comment='P_C (Watts)'),
    sa.Column('phase_c_apparent_power_va', sa.Numeric(precision=14, scale=4), nullable=True, comment='S_C (VA)'),
    sa.Column('phase_c_reactive_power_var', sa.Numeric(precision=14, scale=4), nullable=True, comment='Q_C (VAR)'),
    sa.Column('total_active_power_w', sa.Numeric(precision=14, scale=4), nullable=True, comment='P_total = P_A + P_B + P_C (Watts)'),
    sa.Column('total_apparent_power_va', sa.Numeric(precision=14, scale=4), nullable=True, comment='S_total (VA)'),
    sa.Column('total_reactive_power_var', sa.Numeric(precision=14, scale=4), nullable=True, comment='Q_total (VAR)'),
    sa.Column('total_power_factor', sa.Numeric(precision=6, scale=5), nullable=True, comment='Weighted average PF across all phases'),
    sa.Column('is_valid', sa.Boolean(), server_default='true', nullable=False, comment='False if any validation rule rejected this reading'),
    sa.Column('is_duplicate', sa.Boolean(), server_default='false', nullable=False, comment='True if this packet was identified as a duplicate of another'),
    sa.Column('is_out_of_order', sa.Boolean(), server_default='false', nullable=False, comment='True if this packet arrived after a later-timestamped packet'),
    sa.Column('validation_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Machine-readable validation failure details. Example: {"voltage_out_of_range": {"phase": "A", "value": 280.5}}'),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Original JSON payload from the device for forensic replay'),
    sa.Column('ingest_latency_ms', sa.Integer(), nullable=True, comment='Milliseconds between received_at and storage commit'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('phase_a_power_factor IS NULL OR (phase_a_power_factor >= -1.0 AND phase_a_power_factor <= 1.0)', name='ck_telemetry_pf_a_range'),
    sa.CheckConstraint('phase_a_voltage IS NULL OR phase_a_voltage >= 0', name='ck_telemetry_voltage_a_nonneg'),
    sa.CheckConstraint('phase_b_power_factor IS NULL OR (phase_b_power_factor >= -1.0 AND phase_b_power_factor <= 1.0)', name='ck_telemetry_pf_b_range'),
    sa.CheckConstraint('phase_b_voltage IS NULL OR phase_b_voltage >= 0', name='ck_telemetry_voltage_b_nonneg'),
    sa.CheckConstraint('phase_c_power_factor IS NULL OR (phase_c_power_factor >= -1.0 AND phase_c_power_factor <= 1.0)', name='ck_telemetry_pf_c_range'),
    sa.CheckConstraint('phase_c_voltage IS NULL OR phase_c_voltage >= 0', name='ck_telemetry_voltage_c_nonneg'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Raw telemetry readings from ESP32 smart meters (append-only)'
    )
    op.create_index('ix_telemetry_device_recorded', 'telemetry_readings', ['device_id', 'recorded_at'], unique=False)
    op.create_index('ix_telemetry_device_seq', 'telemetry_readings', ['device_id', 'sequence_number'], unique=False)
    op.create_index('ix_telemetry_is_valid', 'telemetry_readings', ['is_valid'], unique=False)
    op.create_index('ix_telemetry_received_at', 'telemetry_readings', ['received_at'], unique=False)
    op.create_table('anomaly_records',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('telemetry_id', sa.UUID(), nullable=True, comment='The triggering telemetry reading (if applicable)'),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False, comment='Type from AnomalyType enum'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='LOW | MEDIUM | HIGH | CRITICAL'),
    sa.Column('phase', sa.String(length=1), nullable=True, comment="'A', 'B', 'C' for phase-specific; NULL for system-level"),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False, comment='When the anomaly was first detected'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='When the anomaly resolved (auto or manual)'),
    sa.Column('duration_seconds', sa.Numeric(precision=14, scale=3), nullable=True, comment='Computed duration (resolved_at - detected_at)'),
    sa.Column('metric_value', sa.Numeric(precision=16, scale=6), nullable=True, comment='The actual sensor value that triggered the anomaly'),
    sa.Column('threshold_value', sa.Numeric(precision=16, scale=6), nullable=True, comment='The threshold value at detection time'),
    sa.Column('metric_unit', sa.String(length=20), nullable=True, comment='Unit of measurement (V, A, %, W, etc.)'),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_resolved', sa.Boolean(), server_default='false', nullable=False, comment='True if resolved automatically by the system'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable description of the anomaly'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='Notes entered when resolving the anomaly'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional context (e.g., all 3 phase values at detection time)'),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True, comment='User who acknowledged this anomaly'),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp (UTC)'),
    sa.CheckConstraint("phase IS NULL OR phase IN ('A', 'B', 'C')", name='ck_anomaly_phase_valid'),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_at >= detected_at', name='ck_anomaly_resolved_after_detected'),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telemetry_id'], ['telemetry_readings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Detected electrical and data quality anomalies'
    )
    op.create_index('ix_anomaly_device_detected', 'anomaly_records', ['device_id', 'detected_at'], unique=False)
    op.create_index('ix_anomaly_device_unresolved', 'anomaly_records', ['device_id', 'is_resolved'], unique=False)
    op.create_index('ix_anomaly_is_resolved', 'anomaly_records', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_anomaly_records_created_at'), 'anomaly_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_anomaly_records_id'), 'anomaly_records', ['id'], unique=False)
    op.create_index('ix_anomaly_type_severity', 'anomaly_records', ['anomaly_type', 'severity'], unique=False)
    op.create_table('energy_accumulations',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('from_telemetry_id', sa.UUID(), nullable=True, comment='Previous reading (NULL for very first reading of a device)'),
    sa.Column('to_telemetry_id', sa.UUID(), nullable=False, comment='Current reading that defines this interval'),
    sa.Column('from_recorded_at', sa.DateTime(timezone=True), nullable=True, comment='recorded_at of the FROM reading (NULL for first reading)'),
    sa.Column('to_recorded_at', sa.DateTime(timezone=True), nullable=False, comment='recorded_at of the TO reading (partition/range query key)'),
    sa.Column('delta_seconds', sa.Numeric(precision=14, scale=6), nullable=False, comment='Elapsed seconds between from and to readings (exact)'),
    sa.Column('active_energy_wh', sa.Numeric(precision=20, scale=6), nullable=False, comment='P_total × delta_seconds / 3600 — stored in Wh NOT kWh'),
    sa.Column('time_of_day_bucket', sa.String(length=10), nullable=False, comment='DAY | PEAK | NIGHT — based on device timezone at to_recorded_at'),
    sa.Column('is_gap_filled', sa.Boolean(), server_default='false', nullable=False, comment='True if delta_seconds exceeds the expected interval by > 3×'),
    sa.Column('expected_delta_seconds', sa.Numeric(precision=10, scale=3), nullable=True, comment="Device's configured interval at ingestion time (for gap ratio)"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key — UUID v4'),
    sa.CheckConstraint('active_energy_wh >= 0', name='ck_energy_acc_wh_nonneg'),
    sa.CheckConstraint('delta_seconds > 0', name='ck_energy_acc_delta_positive'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_telemetry_id'], ['telemetry_readings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_telemetry_id'], ['telemetry_readings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Per-interval energy delta — atomic unit of energy accounting'
    )
    op.create_index('ix_energy_acc_device_bucket', 'energy_accumulations', ['device_id', 'time_of_day_bucket'], unique=False)
    op.create_index('ix_energy_acc_device_to_ts', 'energy_accumulations', ['device_id', 'to_recorded_at'], unique=False)
    op.create_index('ix_energy_acc_to_telemetry_id', 'energy_accumulations', ['to_telemetry_id'], unique=False)
    op.create_index(op.f('ix_energy_accumulations_id'), 'energy_accumulations', ['id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Structured event type from SystemEventType enum'),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Event-type-specific structured data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomaly_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Structured business events (device state, tariff changes, etc.)'
    )
    op.create_index('ix_system_events_created_at', 'system_events', ['created_at'], unique=False)
    op.create_index('ix_system_events_device_id', 'system_events', ['device_id'], unique=False)
    op.create_index('ix_system_events_type', 'system_events', ['event_type'], unique=False)
    op.create_index('ix_system_events_type_created', 'system_events', ['event_type', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_id', sa.UUID(), nullable=True),
    sa.Column('system_event_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment='ANOMALY_ALERT | BILLING_SUMMARY | DEVICE_OFFLINE | SYSTEM | etc.'),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Delivery channel config: {"in_app": true, "sms": false, "push": true}'),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomaly_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_event_id'], ['system_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='User-facing alerts generated from anomalies and system events'
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_device_id', 'notifications', ['device_id'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_device_id', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_system_events_type_created', table_name='system_events')
    op.drop_index('ix_system_events_type', table_name='system_events')
    op.drop_index('ix_system_events_device_id', table_name='system_events')
    op.drop_index('ix_system_events_created_at', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_energy_accumulations_id'), table_name='energy_accumulations')
    op.drop_index('ix_energy_acc_to_telemetry_id', table_name='energy_accumulations')
    op.drop_index('ix_energy_acc_device_to_ts', table_name='energy_accumulations')
    op.drop_index('ix_energy_acc_device_bucket', table_name='energy_accumulations')
    op.drop_table('energy_accumulations')
    op.drop_index('ix_anomaly_type_severity', table_name='anomaly_records')
    op.drop_index(op.f('ix_anomaly_records_id'), table_name='anomaly_records')
    op.drop_index(op.f('ix_anomaly_records_created_at'), table_name='anomaly_records')
    op.drop_index('ix_anomaly_is_resolved', table_name='anomaly_records')
    op.drop_index('ix_anomaly_device_unresolved', table_name='anomaly_records')
    op.drop_index('ix_anomaly_device_detected', table_name='anomaly_records')
    op.drop_table('anomaly_records')
    op.drop_index('ix_telemetry_received_at', table_name='telemetry_readings')
    op.drop_index('ix_telemetry_is_valid', table_name='telemetry_readings')
    op.drop_index('ix_telemetry_device_seq', table_name='telemetry_readings')
    op.drop_index('ix_telemetry_device_recorded', table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    op.drop_index('ix_tariff_tod_windows_version', table_name='tariff_tod_windows')
    op.drop_index(op.f('ix_tariff_tod_windows_id'), table_name='tariff_tod_windows')
    op.drop_table('tariff_tod_windows')
    op.drop_index(op.f('ix_tariff_tod_modifiers_id'), table_name='tariff_tod_modifiers')
    op.drop_table('tariff_tod_modifiers')
    op.drop_index('ix_tariff_slabs_version', table_name='tariff_slabs')
    op.drop_index(op.f('ix_tariff_slabs_id'), table_name='tariff_slabs')
    op.drop_table('tariff_slabs')
    op.drop_index('ix_energy_monthly_device_ym', table_name='energy_monthly_aggregates')
    op.drop_index(op.f('ix_energy_monthly_aggregates_id'), table_name='energy_monthly_aggregates')
    op.drop_index(op.f('ix_energy_monthly_aggregates_created_at'), table_name='energy_monthly_aggregates')
    op.drop_table('energy_monthly_aggregates')
    op.drop_index('ix_energy_hourly_device_hour', table_name='energy_hourly_aggregates')
    op.drop_index(op.f('ix_energy_hourly_aggregates_id'), table_name='energy_hourly_aggregates')
    op.drop_index(op.f('ix_energy_hourly_aggregates_created_at'), table_name='energy_hourly_aggregates')
    op.drop_table('energy_hourly_aggregates')
    op.drop_index('ix_energy_daily_device_date', table_name='energy_daily_aggregates')
    op.drop_index(op.f('ix_energy_daily_aggregates_id'), table_name='energy_daily_aggregates')
    op.drop_index(op.f('ix_energy_daily_aggregates_created_at'), table_name='energy_daily_aggregates')
    op.drop_table('energy_daily_aggregates')
    op.drop_index('ix_device_locations_pincode', table_name='device_locations')
    op.drop_index(op.f('ix_device_locations_id'), table_name='device_locations')
    op.drop_index(op.f('ix_device_locations_created_at'), table_name='device_locations')
    op.drop_table('device_locations')
    op.drop_index(op.f('ix_device_health_records_id'), table_name='device_health_records')
    op.drop_index('ix_device_health_is_online', table_name='device_health_records')
    op.drop_index('ix_device_health_device_recorded', table_name='device_health_records')
    op.drop_table('device_health_records')
    op.drop_index(op.f('ix_device_configurations_id'), table_name='device_configurations')
    op.drop_index(op.f('ix_device_configurations_created_at'), table_name='device_configurations')
    op.drop_table('device_configurations')
    op.drop_index('ix_device_auth_tokens_token_hash', table_name='device_auth_tokens')
    op.drop_index(op.f('ix_device_auth_tokens_id'), table_name='device_auth_tokens')
    op.drop_index(op.f('ix_device_auth_tokens_created_at'), table_name='device_auth_tokens')
    op.drop_table('device_auth_tokens')
    op.drop_index(op.f('ix_billing_snapshots_id'), table_name='billing_snapshots')
    op.drop_index(op.f('ix_billing_snapshots_created_at'), table_name='billing_snapshots')
    op.drop_index('ix_billing_owner_period', table_name='billing_snapshots')
    op.drop_index('ix_billing_is_projected', table_name='billing_snapshots')
    op.drop_index('ix_billing_device_type', table_name='billing_snapshots')
    op.drop_index('ix_billing_device_period', table_name='billing_snapshots')
    op.drop_table('billing_snapshots')
    op.drop_index('ix_user_api_keys_user_id', table_name='user_api_keys')
    op.drop_index('ix_user_api_keys_key_hash', table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_tariff_versions_id'), table_name='tariff_versions')
    op.drop_index('ix_tariff_versions_effective_to', table_name='tariff_versions')
    op.drop_index(op.f('ix_tariff_versions_created_at'), table_name='tariff_versions')
    op.drop_index('ix_tariff_versions_category_effective', table_name='tariff_versions')
    op.drop_table('tariff_versions')
    op.drop_index('ix_devices_status', table_name='devices')
    op.drop_index('ix_devices_serial_number', table_name='devices')
    op.drop_index('ix_devices_owner_status', table_name='devices')
    op.drop_index('ix_devices_owner_id', table_name='devices')
    op.drop_index('ix_devices_last_seen_at', table_name='devices')
    op.drop_index(op.f('ix_devices_is_deleted'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_created_at'), table_name='devices')
    op.drop_index('ix_devices_connection_type', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_audit_logs_table_record', table_name='audit_logs')
    op.drop_index('ix_audit_logs_changed_by', table_name='audit_logs')
    op.drop_index('ix_audit_logs_changed_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index('ix_users_is_active_deleted', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tariff_categories_id'), table_name='tariff_categories')
    op.drop_index(op.f('ix_tariff_categories_created_at'), table_name='tariff_categories')
    op.drop_index('ix_tariff_categories_code', table_name='tariff_categories')
    op.drop_table('tariff_categories')
    # ### end Alembic commands ###
